name: Version

on:
  # release: 
  #   types: [published]
  workflow_dispatch: 
permissions:
  contents: write
  pull-requests: write

jobs:
  deliver:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          docker build --tag application:${{ github.event.release.tag_name }} --file src/Dockerfile .