name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        name: Release Please
        with:
          token: ${{ secrets.PAT }}
          release-type: 'simple'
      - if: ${{ steps.release.outputs.release_created == 'true' }}
        run: |
          docker build --tag application:${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }} --file src/Dockerfile .